### ISSUE TITLE
Examples for all features

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/prom-attire-rs#5]
Currently there's just the one basic example. The docs should be extended to show all the different features. There should be tests covering them all so basically need to take a good subset of the tests, clean them up, add some notes, and put them in the crate docs.

Quick list of what features I can think of right now:

 - [x] `attire(scope)` - setting a wrapper attribute
 - [x] `attire(default)` - setting a default if unspecified
 - [x] `FromStr` parsing - parsing strings passed in as values
 - [ ] `attire(docs)` - putting docs attributes into a place
 - [ ] `attire(attribute)` - setting a different attribute name to use (#9)
 - [ ] `attire(split_attribute_of)` - complicated, semi-unstable (#10)
 - [ ] `attire(flag_value)` - set a default if the attribute is used without a value, (#11)
 - [ ] literals - support for non-string literals (currently unstable in Rust, but supported by `syn`)
 - [ ] `bool` - special cased `default` and `flag_value`
 - [x] `Vec` - attributes that can take multiple values
 - [x] errors - the errors that can be returned during parsing
 - [x] lifetimes - borrowing strings from the AST
